### ISSUE TITLE
Fatal error: Call to undefined method stdClass::userdata() in ext.dashee.php on line 126

### ISSUE THREAD

**Issue by tyssen** [mrtopher/dashEE#29] opened 2013-05-24 03:15 UTC
I just updated to the latest version of dashEE and am getting this error when trying to access the control panel.

**Comment by putyourlightson** [comment] 2013-05-24 12:40
am also getting this with dashEE 1.8 and EE 2.6.1

**Comment by mrtopher** [comment] 2013-05-24 18:48
Oops, sorry about that. I pushed a fix so if you download the latest it should be resolved now.

**Comment by tyssen** [comment] 2013-05-25 21:55
I've updated to the latest version but when trying to add widgets I get:

> The requested module page could not be found.

**Comment by mrtopher** [comment] 2013-05-26 14:54
Are you getting this message when you click the "Widgets" button or when you go to add a specific widget? I'm unable to reproduce.

**Comment by tyssen** [comment] 2013-05-26 22:16
When clicking on the Widgets button.

**Comment by mrtopher** [comment] 2013-05-29 23:21
This is strange, are you still experiencing this problem? I'm unable to reproduce.

**Comment by tyssen** [comment] 2013-05-29 23:50
Actually, no it seems to be fine now. :? No idea why it's OK now but not before. Sorry for troubling you.

**Comment by mrtopher** [comment] 2013-05-29 23:52
No trouble. Glad everything is working now.

**Closed as completed by mrtopher** 2013-05-29 23:52 UTC

**Comment by CNG** [comment] 2013-10-23 07:08
Hi there, I haven’t found any reference to someone having this same problem upgrading to 2.7.1 or 2.7.2, so perhaps this is due to the highly irregular nature of the install I’m working with. Upon upgrading from 2.5.2 with the latest DashEE, I get this error:

```
Fatal error: Call to undefined method stdClass::userdata() in /var/www/portal/application/third_party/dashee/models/dashee_model.php on line 32
```

Any thoughts on what I can check to troubleshoot this?

Thanks!

**Comment by mrtopher** [comment] 2013-10-28 13:06
Sorry for the late response CNG. I have installed the latest release of EE (2.7.2), tried dashEE and have not experienced any issues. Are you still having problems? Is this a persistent issue or something you only see when upgrading and then it goes away? 

Also, can you tell me what, if any, other modules you are using?

**Comment by CNG** [comment] 2013-10-28 15:41
Hi, no worries, thanks for looking into it. After further testing, I discovered I could not upgrade from 2.5.2 to 2.7.1 or 2.7.2 with DashEE installed, but if I uninstalled it, upgraded, and then reinstalled it, it worked fine. Here are all the addons installed on this system: http://imgur.com/C2xNXp3

I can try the one by one uninstalling if nothing sticks out to you.

**Comment by CNG** [comment] 2013-10-28 23:36
I did another test where I started with the 2.5.2 installation and uninstalled every single module, extension, plugin, fieldtype, etc., and removed all the files from my third_party folder, except for DashEE. The upgrade to 2.7.2 still did not work, resulting in this error, apparently on the final 2.7.2 step, but I think it appeared to be on the final 2.7.1 step when I was previously trying to upgrade to 2.7.1: http://imgur.com/akRqkHz

**Comment by CNG** [comment] 2013-10-28 23:43
Also, if it helps, I found that I get the error with DashEE module installed but extension uninstalled, and I do not get the error if I uninstall DashEE module but leave the extension installed.
